
export const SYS_RANGE_START = 0x00;
export const SYSTEM_SEQUENCE_CONFIG = 0x01;
export const SYSTEM_INTERRUPT_CONFIG_GPIO = 0x0a;
export const SYSTEM_INTERRUPT_CLEAR = 0x0b;

export const RESULT_RANGE_STATUS = 0x14;

export const FINAL_RANGE_CONFIG_MIN_COUNT_RATE_RTN_LIMIT = 0x44;
export const DYNAMIC_SPAD_NUM_REQUESTED_REF_SPAD = 0x4e;
export const DYNAMIC_SPAD_REF_EN_START_OFFSET = 0x4f;

export const PRE_RANGE_CONFIG_VCSEL_PERIOD = 0x50;
export const FINAL_RANGE_CONFIG_VCSEL_PERIOD = 0x70;

export const MSRC_CONFIG_TIMEOUT_MACROP = 0x46;
export const PRE_RANGE_CONFIG_TIMEOUT_MACROP_HI = 0x51;
export const FINAL_RANGE_CONFIG_TIMEOUT_MACROP_HI = 0x71;

export const MSRC_CONFIG_CONTROL = 0x60;

export const GPIO_HV_MUX_ACTIVE_HIGH = 0x84;

export const GLOBAL_CONFIG_SPAD_ENABLES_REF_0 = 0xb0;
export const GLOBAL_CONFIG_REF_EN_START_SELECT = 0xb6;
