export const PARAMETER_OUT_OF_RANGE_START = 0;
export const PARAMETER_OUT_OF_RANGE_END = 9;

export const DIGITAL_CHANNEL_NOT_CONFIGURED_FOR_OUTPUT_START = 10;
export const DIGITAL_CHANNEL_NOT_CONFIGURED_FOR_OUTPUT_END = 17;
export const NO_DIGITAL_CHANNELS_CONFIGURED_FOR_OUTPUT = 18;

export const DIGITAL_CHANNEL_NOT_CONFIGURED_FOR_INPUT_START = 20;
export const DIGITAL_CHANNEL_NOT_CONFIGURED_FOR_INPUT_END = 27;
export const NO_DIGITAL_CHANNELS_CONFIGURED_FOR_INPUT = 28;

export const SERVO_NOT_FULLY_CONFIGURED = 30;
export const BATTERY_VOLTAG_TOO_LOW_TO_RUN_SERVO = 31;

export const I2C_CONTROLLER_BUSY = 40;
export const I2C_OPERATION_IN_PROGRESS = 41;
export const I2C_NO_RESULTS_PENDING = 42;
export const I2C_QUERY_MISMATCH = 43;
export const I2C_TIMEOUT_SDA_STUCK = 44;
export const I2C_TIMEOUT_SCL_STUCK = 45;
export const I2C_TIMEOUT = 46;

export const MOTOR_NOT_FULLY_CONFIGURED = 50;
export const COMMAND_NOT_VALID_FOR_SELECTED_MOTOR_MODE = 51;
export const BATTERY_VOLTAGE_TOO_LOW_TO_RUN_MOTOR = 52;

export const COMMAND_IMPLEMENTATION_PENDING = 253;
export const COMMAND_ROUTING_ERROR = 254;
export const COMMAND_NOT_SUPPORTED = 255;
