export * from "./errors/RhspLibError.js";
export * from "./discovery.js";
export {
    openParentExpansionHub,
    openExpansionHubAndAllChildren,
} from "./open-rev-hub.js";

export {
    createLedPattern,
    BatteryTooLowError,
    BatteryTooLowToRunMotorError,
    BatteryTooLowToRunServoError,
    BulkInputData,
    ClosedLoopControlAlgorithm,
    CommandImplementationPendingError,
    CommandNotSupportedError,
    CommandRoutingError,
    DebugGroup,
    DigitalChannelDirection,
    DigitalChannelNotConfiguredForInputError,
    DigitalChannelNotConfiguredForOutputError,
    DigitalState,
    DiscoveredAddresses,
    ExpansionHub,
    GeneralSerialError,
    I2CReadStatus,
    I2CSpeedCode,
    I2CWriteStatus,
    I2cControllerBusyError,
    I2cNoResultsPendingError,
    I2cOperationInProgressError,
    I2cQueryMismatchError,
    I2cTimeoutError,
    I2cTimeoutSclStuckError,
    I2cTimeoutSdaStuckError,
    LedPattern,
    LedPatternStep,
    ModuleInterface,
    ModuleStatus,
    MotorCommandNotValidError,
    MotorMode,
    MotorNotFullyConfiguredError,
    NackError,
    NoDigitalChannelsConfiguredForInputError,
    NoDigitalChannelsConfiguredForOutputError,
    NoExpansionHubWithAddressError,
    ParameterOutOfRangeError,
    PidCoefficients,
    PidfCoefficients,
    RevHub,
    RevHubError,
    Rgb,
    SerialIoError,
    ServoNotFullyConfiguredError,
    TimeoutError,
    UnableToOpenSerialError,
    UnrecognizedNackError,
    VerbosityLevel,
    Version,
} from "@rev-robotics/rev-hub-core";
