name: Cross Compile

on:
  workflow_dispatch:

jobs:
  cross-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Check available cross-compilers
        run: dpkg --list | grep cross-build
